### ISSUE TITLE
Missing preference data store

### ISSUE THREAD

**Issue by Mygod** [RikkaW/MaterialPreference#15]
Great library! However the thing that keeps me from using it is that it's missing `PreferenceManager.setPreferenceDataStore`. Is it possible to base this library off Android support preference library instead?

**Comment by RikkaW** [comment]
At first, this library was based on support library 23.2.0, so things added in later Android version is missing. I will add them in recent days.
And the reason why this this library is not just extend classes in support library is support library hard-coded to use `android.app.AlertDialog` (and some other things that have to modify the code directly).
